### PR TITLE
Kotlin & AndroidX conversion

### PR DESCRIPTION
**Pull request by Doomsdayrs**
- Converted application to androidx
- Converted application to kotlin
- Applied kotlin techniques to simplify some code

### CODE REVIEW

**Comment by sarbajitsaha** [comment]
I am getting the following error while trying to run this change. 

`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.saha.batchuninstaller/com.saha.batchuninstaller.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference`

Seems like in this line

`private val mPrefs: SharedPreferences = PreferenceManager.getDefaultSharedPreferences(applicationContext)`

applicationContext is null?

Have you tried running your changes in a device?

**Comment by Doomsdayrs** [comment]
That should fix it~

**Comment by sarbajitsaha** [comment]
Thanks! The code looks good. I just need a couple more changes, and I can merge it to master. 

1. Running Code inspection shows that we have unnecessary safe calls on mEditor. Can you please remove the ? wherever mEditor is read. Those aren't needed. 

2. This isn't related to your change, but would be great if I can merge together. The day and night modes often didn't work properly on this application.
Based on this[ link,](https://stackoverflow.com/questions/58481456/night-mode-color-is-not-applying-to-the-recycler-view-background) seem like replacing applicationContext with this@MainActivity in the AppInfo adapter does the trick. 
If possible, please change that as well, 

In line 130, 		mAdapter = AppInfoAdapter(applicationContext, mApps)
change applicationContext to this@MainActivity


Once done, let me know. I will merge.

**Comment by Doomsdayrs** [comment]
:+1:

**Comment by sarbajitsaha** [comment]
Merged to master. Thanks for the change!

**Pull request merged**
