### PR TITLE
some maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- delete .idea and extra .aar files
- target android pie
- java 1.8 compatibility
- reformat code
- rearrange strings.xml
- migrate app to appCompat
- dialogs lib 0.9.4.5 -> 0.9.6.0
- recyclerviewhelper 27.1.0 -> 27.1.1
- note that EasyLicensesDialog is deprecated, recommend switching to Licenser

### CODE REVIEW

**Comment by sarbajitsaha** [comment]
Thanks for the pull request. 

I noticed that you have changed the license term "You should have received a copy" to "You should have received a donate_copy" in some of the .java files. I am guessing its a refactoring error.
The current version is the correct one; please refer here - https://www.gnu.org/licenses/gpl-howto.en.html  

Once its fixed, I will merge after doing a successful build.

**Comment by TacoTheDank** [comment]
yeah that was refactoring that changed those for some reason

**Comment by TacoTheDank** [comment]
@sarbajitsaha Just a reminding mention

**Review by sarbajitsaha — APPROVED** [review]

**Comment by TacoTheDank** [comment]
Thanks :)

**Pull request merged**
